import React, { useContext, useEffect, useState } from "react";
import OrderHistory from "../OrderHistory/orderHistory";
import { Row, Col } from "react-bootstrap";
import { PublicLayout } from "../Layout/PublicLayout";
import Head from "next/head";
import {collection, getDocs} from "firebase/firestore";
import {db} from "../../FirebaseConfig";

const breadcrumbsData = [
    {
        label: 'Home',
        path: '/',
    },
    {
        label: 'Order History',
        path: '/OrderHistory',
    }
];

const Orders = () => { //this is the index page for order history
    return (
        <>
            <Head>
                <title>DFM</title>
                <meta name="description" content="Generated by create next app"/>
                {/*<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@latest/dist/tailwind.min.css"/>*/}
                <link rel="icon" href="https://firebasestorage.googleapis.com/v0/b/diasspora-94216.appspot.com/o/Diasspora%20Finals%2FDiasspora%20Icon%20With%20No%20Text-29.png?alt=media&token=f857f5f7-17b4-48f4-8b45-0c39ca9fa893"/>
            </Head>
            <PublicLayout breadcrumb={breadcrumbsData} breadcrumbTitle='OrderHistory'>
            <OrderHistory />
            </PublicLayout>
        </>
    );
};

export default Orders;
