import { Breadcrumb } from "../Breadcrumb/Breadcrumb";
import { Layout } from "./Layout";
import Head from "next/head";

export const PublicLayout = ({ // layout for the website
  children,
  breadcrumb,
  breadcrumbTitle,
  description,
  
}) => {
  return (
    <Layout>
      <Head>
        <title>DFM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://firebasestorage.googleapis.com/v0/b/diasspora-94216.appspot.com/o/Diasspora%20Finals%2FDiasspora%20Icon%20With%20No%20Text-29.png?alt=media&token=f857f5f7-17b4-48f4-8b45-0c39ca9fa893" />
      </Head>
      <Breadcrumb
        breadcrumb={breadcrumb}
        title={breadcrumbTitle}
        description={description}
      />
      <>{children}</>
    </Layout>
  );
};
export default PublicLayout;